<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>

___

<a href="https://lms.clarusway.com/course/view.php?id=37"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/3-DVwPY/DVwPy_S06_Capstone_Project%20(Bike%20Store%20Sharing).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="100" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DVwPY_S6/6-DVwPy%20Capstone%20%28Bike%20Store%20Sharing%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="130" height="200" title="Open and Execute in nbviewer"></a><br/>
___

<a href="https://clarusway.com/"><img align="center" src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" alt="CLRSWY" width="450" height="200" title="Welcome to Place Where You can Reinvent Yourself"></a><br/>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:120%; text-align:center; border-radius:10px 10px;">Way to Reinvent Yourself</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

# How can we convert a Series to DataFrame?

In order to convert a pandas Series to a DataFrame, we can use the .to_frame() method. 
Here's an example:

In [73]:
import pandas as pd

s = pd.Series([20,18,54])

s

0    20
1    18
2    54
dtype: int64

In [74]:
df = pd.DataFrame(data=s, columns=["price"])
df

price
0     20
1     18
2     54

In [75]:
df = s.to_frame(name="Price")

df

Price
0     20
1     18
2     54

In [76]:
courses = pd.Series(["Spark","PySpark","Hadoop"])
fees = pd.Series([22000,25000,23000])
discount  = pd.Series([1000,2300,1000])

df = pd.concat([courses,fees,discount],axis=1)
df

0      1     2
0    Spark  22000  1000
1  PySpark  25000  2300
2   Hadoop  23000  1000

# How can we convert String to date?

In [77]:
#Example 1: Converting a single string to a date:
date_string = '2023-07-12'
date = pd.to_datetime(date_string)
date
#Timestamp object

Timestamp('2023-07-12 00:00:00')

In [78]:
#Example 2: Converting a column of strings in a DataFrame to dates:
data = {'DateColumn': ['2023-07-12', '2023-07-13', '2023-07-14']}
df = pd.DataFrame(data)

df['DateColumn'] = pd.to_datetime(df['DateColumn'])
df

DateColumn
0 2023-07-12
1 2023-07-13
2 2023-07-14

In [79]:
#Example 3: Converting strings with specific date format
date_strings = ['12-07-2023', '13-07-2023', '14-07-2023']
dates = pd.to_datetime(date_strings, format='%d-%m-%Y')
dates

data = {'DateColumn': ['2023-07-12', '2023-07-13', '2023-07-14']}
df = pd.DataFrame(data)

df['DateColumn'] = pd.to_datetime(df['DateColumn'])
df

DateColumn
0 2023-07-12
1 2023-07-13
2 2023-07-14

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [80]:
import numpy as np

### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [81]:
np.arange(5,26,5)

array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [82]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [83]:
np.ones((4,4), dtype=int) # default dtype is float

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [84]:
np.ones((4,4), dtype=int)*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [85]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (both inclusive). 

In [86]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 (inclusive) to 25 (exclusive).

In [87]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 (inclusive) to 25 (exclusive) using linspace method.

In [88]:
np.linspace(0, 24, num=25 ,dtype=int).reshape(5,5) 
#.linspace() method has a default "endpoint= True" parameter

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [89]:
np.linspace(0, 25, num=25 ,dtype=int, endpoint=False).reshape(5,5) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 10. Create randomly 5 numbers with numpy.

In [90]:
np.random.rand(5)

array([0.10425119, 0.98218089, 0.92625465, 0.92205182, 0.6195558 ])

### 11. Generate a 5 by 5 array and fills it with random values as per the standard normal distribution.


In [91]:
np.random.randn(25).reshape(5,5)

array([[ 0.52683497, -0.39022415,  2.24138396,  0.87655421,  2.3167003 ],
       [-0.31992834, -1.76756501,  0.42727448,  1.16255995,  0.24713037],
       [ 0.13808851, -0.69390581, -0.47659196, -1.38891528,  0.03250594],
       [-0.06945306, -1.26410109, -0.41999772, -0.179895  ,  0.60691435],
       [-0.20891549,  0.95862848, -0.22196626,  0.75412407,  0.05569172]])

### 12. Generate a 3*4 array of random int numbers between 20 and 50 (both inclusive).

In [92]:
np.random.randint(20,51, size= (3,4))

array([[35, 33, 23, 26],
       [49, 27, 20, 25],
       [48, 43, 32, 31]])

### 13. Generate an array named "ranarr"consisting of randomly 48 numbers (int) and reshape this array 6 by 8 in different ways (remember the power of -1).

In [93]:
ranarr = np.random.randint(1, 100, size=48) 
#the range is not specified. 1(incl.) and 100(excl.) are assigned to the lowest and highest limits respectively.
ranarr

array([15, 21, 63, 77, 51, 12, 23, 79,  7, 92, 79,  8, 45,  9,  4,  9, 24,
       52, 14,  6, 78, 92, 53, 10, 23, 68, 57, 35, 95, 77, 65, 46, 16, 44,
       28,  9, 61,  4, 61, 97, 31, 70, 31, 49, 70, 17, 94, 49])

In [94]:
ranarr = np.random.randint(1, 100, size=48).reshape(6,8)
ranarr

array([[55, 32, 38, 49, 84,  1, 65, 86],
       [ 3, 31, 45, 17, 57, 75, 59, 37],
       [28, 52, 61, 89, 71, 67, 82, 99],
       [29, 91, 53, 35, 44, 92, 70, 39],
       [40, 46, 61, 75, 16, 68, 91, 36],
       [38, 12, 77, 94, 74, 67, 81, 76]])

In [95]:
ranarr = np.random.randint(1, 100, size=48).reshape(6,-1) 
# if only the number of col/row is known, with -1, the number of row/col is automatically calculated by Python 
ranarr

array([[30, 91,  6, 97, 76, 40, 33, 12],
       [ 7, 93, 28, 48, 26, 41, 77, 68],
       [40, 93, 16, 84, 78, 11, 37, 88],
       [47, 33,  8, 44, 71, 61, 46, 24],
       [30, 28, 23,  1, 60, 87, 27, 85],
       [18, 57, 70, 54, 61, 94, 86,  6]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [96]:
mat = np.arange(1,17).reshape(4,4)

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [97]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [98]:
mat[:,0] 

array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [99]:
mat[1,::2] #::x shows the number of steps

array([5, 7])

### 17. Assign 77 to every cell in 3rd column (index number 2).

In [100]:
mat[:,2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take the value at the 2nd row (index number 1) and 1st column (index number 0) & (b) the value at the 4th row (index number 3) and 3rd column (index number 2) at the same time.

In [101]:
mat[[1,3],[0,2]]

array([ 5, 77])

### 19. What are the common values present at the intersection of the second (index number 1) and last (index number 3) row with a step size of 2 and the first (index number 0) and last column with a step size of 2 in the given array?

In [102]:
np.array([mat[1,::2], mat[3,::2]])

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [103]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [104]:
mat[mat<10]

array([1, 2, 4, 5, 6, 8, 9])

In [105]:
mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [106]:
mat[mat<10]+mat[mat>12]

array([78, 79, 81, 18, 20, 85, 25])

In [107]:
mat[(mat<10)|(mat>12)].sum()

386

### 21. Get the standard deviation (std) of the result above.

In [108]:
matSum = mat[mat<10]+mat[mat>12]
matSum.std()

29.700546274093877

### 22. Get the sum of the values at the 2nd column (index number 1) in the original "mat".

In [109]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [110]:
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [111]:
mat[:,1].sum() 

32

### 23. Get the median, mean and std of 3rd column in "mat".

In [112]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [113]:
var3 = mat[:,[2]]
var3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [114]:
row3 = mat[2,:]
row3

array([ 9, 10, 11, 12])

In [115]:
print(np.median(var3),"\n",np.median(row3))

9.0 
 10.5


In [116]:
print(np.mean(var3),"\n",np.mean(row3))


9.0 
 10.5


In [117]:
print(np.std(var3),"\n", np.std(row3))

4.47213595499958 
 1.118033988749895


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [118]:
import pandas as pd
import py7zr

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.

In [119]:
with py7zr.SevenZipFile('Salaries.7z', mode='r') as file:
    file.extractall()
    

In [120]:
df = pd.read_csv("Salaries.csv")

In [121]:
df.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [122]:
df.sample(10)

Id       EmployeeName                        JobTitle    BasePay  \
135888  135889           Amy C Li                       Custodian   47913.00   
65345    65346   Eugene Arnold Jr       Automotive Service Worker   12566.30   
109160  109161      Ruilian Z Lam                       Custodian    1426.60   
120344  120345     Rico M Zucconi  Sr Statnry Eng, Wtr Treat Plnt   98100.01   
131241  131242     Peter Chignell         Parking Control Officer   59068.96   
2636      2637  TERRY FITZSIMMONS          FIRE FIGHTER PARAMEDIC  122405.00   
38412    38413        Lamar Toney                Police Officer 3  117723.23   
145424  145425        Man H Yeung          Public Service Trainee    5941.91   
26382    26383        KEVIN SMITH                TRANSIT OPERATOR   37498.71   
9001      9002  CRAIG CHERRINGTON                  DEPUTY SHERIFF   86840.00   

        OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
135888       192.54   1826.74  26939.27   49932.28          76871.55  2014   
65345       1636.00  14324.00   4994.33   28526.30          33520.63  2012   
109160         0.00      0.00    801.16    1426.60           2227.76  2013   
120344       224.94   5770.92  36561.84  104095.87         140657.71  2014   
131241      1986.57   5664.53  27866.59   66720.06          94586.65  2014   
2636       14951.44   7497.84       NaN  144854.28         144854.28  2011   
38412      42763.27   4802.09  35380.01  165288.59         200668.60  2012   
145424         0.00      6.02     59.44    5947.93           6007.37  2014   
26382       4381.06    571.77       NaN   42451.54          42451.54  2011   
9001        3431.93  12446.21       NaN  102718.14         102718.14  2011   

        Notes         Agency  Status  
135888    NaN  San Francisco     NaN  
65345     NaN  San Francisco     NaN  
109160    NaN  San Francisco     NaN  
120344    NaN  San Francisco     NaN  
131241    NaN  San Francisco     NaN  
2636      NaN  San Francisco     NaN  
38412     NaN  San Francisco     NaN  
145424    NaN  San Francisco     NaN  
26382     NaN  San Francisco     NaN  
9001      NaN  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [124]:
df.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

In [125]:
df.describe().T

count          mean           std      min        25%  \
Id                148654.0  74327.500000  42912.857795     1.00  37164.250   
BasePay           148045.0  66325.448840  42764.635495  -166.01  33588.200   
OvertimePay       148650.0   5066.059886  11454.380559    -0.01      0.000   
OtherPay          148650.0   3648.767297   8056.601866 -7058.59      0.000   
Benefits          112491.0  25007.893151  15402.215858   -33.89  11535.395   
TotalPay          148654.0  74768.321972  50517.005274  -618.13  36168.995   
TotalPayBenefits  148654.0  93692.554811  62793.533483  -618.13  44065.650   
Year              148654.0   2012.522643      1.117538  2011.00   2012.000   
Notes                  0.0           NaN           NaN      NaN        NaN   
Status                 0.0           NaN           NaN      NaN        NaN   

                       50%         75%        max  
Id                74327.50  111490.750  148654.00  
BasePay           65007.45   94691.050  319275.01  
OvertimePay           0.00    4658.175  245131.88  
OtherPay            811.27    4236.065  400184.25  
Benefits          28628.62   35566.855   96570.66  
TotalPay          71426.61  105839.135  567595.43  
TotalPayBenefits  92404.09  132876.450  567595.43  
Year               2013.00    2014.000    2014.00  
Notes                  NaN         NaN        NaN  
Status                 NaN         NaN        NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [152]:
df.Year.value_counts()

Year
2014    38123
2013    37606
2012    36766
2011    36159
Name: count, dtype: int64

In [66]:
df.Year.nunique()

4

In [153]:
df.Year.unique()

array([2011, 2012, 2013, 2014], dtype=int64)

### Print out max and avg values in the column of "Totalpay".

In [70]:
df.TotalPay.max()

567595.43

In [71]:
df.TotalPay.mean()

74768.32197169267

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [74]:
df[df.TotalPay>df.TotalPay.mean()]

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [79]:
df[df.TotalPay>df.TotalPay.mean()]["TotalPay"].count()

69489

### How much does ALBERT PARDINI make money (including extras, benefits, etc)?

In [94]:
df[df.EmployeeName == "ALBERT PARDINI"].TotalPayBenefits

2    335279.91
Name: TotalPayBenefits, dtype: float64

### Who is the lowest paid person?

In [100]:
df[df["TotalPay"] == df["TotalPay"].min()].EmployeeName

148653    Joe Lopez
Name: EmployeeName, dtype: object

### What are the unique Jobs in dataset?

In [102]:
df.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [106]:
df.JobTitle.value_counts().tail(3)

JobTitle
COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: count, dtype: int64

### How many people earned more than avg in 2012? (including extras, benefits, etc)

In [130]:
avgTotalPayBenefits2012 = df[df["Year"]==2012]["TotalPayBenefits"].mean()

arr = df[df["Year"]==2012]["TotalPayBenefits"]>avgTotalPayBenefits2012

arr.sum()

18703

In [132]:
#len(df[(df.TotalPayBenefits > df.TotalPayBenefits.mean()) & (df.Year == 2012)]['EmployeeName'].unique())
df[(df.Year == 2012) & (df.TotalPayBenefits > df.TotalPayBenefits.mean())].shape[0]

20366

### How many people have a title of Manager in their jobs?

In [210]:
df[df['JobTitle'].str.contains('manager', case=False)]["JobTitle"].count()

4110

In [133]:
df['JobTitle'].apply(lambda x: 'manager' in x.lower()).sum()

4110

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [214]:
sal_new = df.iloc[:, [0, 1, 2, 7, 8]]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [220]:
sal_new = df.loc[:, "EmployeeName":"TotalPayBenefits"]
sal_new

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

          BasePay  OvertimePay   OtherPay  Benefits   TotalPay  \
0       167411.18         0.00  400184.25       NaN  567595.43   
1       155966.02    245131.88  137811.38       NaN  538909.28   
2       212739.13    106088.18   16452.60       NaN  335279.91   
3        77916.00     56120.71  198306.90       NaN  332343.61   
4       134401.60      9737.00  182234.59       NaN  326373.19   
...           ...          ...        ...       ...        ...   
148649       0.00         0.00       0.00       0.0       0.00   
148650        NaN          NaN        NaN       NaN       0.00   
148651        NaN          NaN        NaN       NaN       0.00   
148652        NaN          NaN        NaN       NaN       0.00   
148653       0.00         0.00    -618.13       0.0    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 8 columns]

Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [229]:
df[(df.TotalPayBenefits > df.TotalPayBenefits.min()) & (df.TotalPayBenefits < df.TotalPayBenefits.mean())][["EmployeeName","TotalPayBenefits"]]

EmployeeName  TotalPayBenefits
10806          KWE LEE          93691.15
10807   MIGUEL CARO JR          93682.74
10808    JOANNE MORRIS          93680.53
10809    LAYLA WELBORN          93676.88
10810          LE BANH          93675.39
...                ...               ...
148648     Leon Walker              0.00
148649   Roy I Tillery              0.00
148650    Not provided              0.00
148651    Not provided              0.00
148652    Not provided              0.00

[75649 rows x 2 columns]

Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________

<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>